### ISSUE TITLE
Differentiate the subheaders more

### ISSUE THREAD

**Issue by ClaudeMetz** [AlternativeFFFF/Alt-F4#114]
Currently, the two types of subheaders we use (`##` and `###` in markdown) appear the [same](https://imgur.com/2uNMkYL)/very similarly on the website. This makes it hard to differentiate where a new submission starts, and what is just a subheader for the submission you're currently reading. Maybe there can be something done with the styling to improve this situation, either by text size or just adding a dividing line or something.

**Comment by nicgarner** [comment]
For example, [this](https://imgur.com/vCF0EQE) is what it would look like if we increased the H2 font size to 150%.
(Might want to keep the anchor/link icon the same size though.)

**Comment by Conor12345** [comment]
Gotta consider mobile too!

**Comment by Conor12345** [comment]
Not convinced a font size change is quite enough to resolve this, maybe a colour change too would help?
Also do H3 (sub headings) need anchors? It might differentiate them more as sub headings if they didn't have them.
Im leaning more towards removing the anchors for subheadings rather than messing with colours.

**Comment by nicgarner** [comment]
Could also add a horizontal dividing line between sections in order to further emphasise the change in section.
