### ISSUE TITLE
[minor] Language popout is not showing selected language

### ISSUE THREAD

**Issue by oof2win2** [AlternativeFFFF/Alt-F4#568]
The language popout is showing English even though I switched it to French (just as an example).
<img width="1212" alt="Screenshot 2021-10-26 at 16 58 17" src="https://user-images.githubusercontent.com/23482862/138905731-d28a97fd-fb1f-41f3-8c8d-b44a045f30c8.png">

This however does not occur on the article pages.
<img width="1197" alt="Screenshot 2021-10-26 at 16 59 42" src="https://user-images.githubusercontent.com/23482862/138906043-248a1861-b5b5-476d-a2d1-4fa4eca80292.png">

**Comment by DrMagPie** [comment]
Finally had a look into it.
It seams that the problem is caused by the way 404 page is implemented.
Technically it is out of `i18n` and translations are hacked into it.
Another interesting bug caused by it:
If we select another language
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/23652900/163631782-ff984080-1215-416c-b661-289626a204cd.png">
then navigate to home page
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/23652900/163631850-6f9b2c48-a57a-4e63-a33b-886e551b8671.png">
<img width="161" alt="image" src="https://user-images.githubusercontent.com/23652900/163631868-366b0896-268b-47fd-8356-88404d2d8616.png">
well, first of all it lead us to English home.
and the second if we then go to a page that doesn't exist we get 404 in previous selected language 
<img width="297" alt="image" src="https://user-images.githubusercontent.com/23652900/163632053-fcaf7ec5-bb70-4620-be6a-738055351683.png">
<img width="435" alt="image" src="https://user-images.githubusercontent.com/23652900/163632074-0615b265-fc04-430c-8167-38f27f4edcfc.png">
When it should have been in English.
